### ISSUE TITLE
Power level divide by 2 with some Halium port

### ISSUE THREAD

**Issue by Vince1171** [ubports/indicator-power#16]
The title is clear (I think). When the battery is fully charged, the indicator displays only 50%. 80% => 40%, etc...

**Comment by 0312birdzhang** [comment]
Same here, xiaomi redmi 5 plus(vince)

**Comment by 0312birdzhang** [comment]
Works for vince( and should works on other phones with only one battery ), not validate other devices with two batteries.

https://github.com/ubports-on-vince/indicator-power/commit/97e773b1a1a2a2e3e5e571d4d1eeb8416c9f75c8

A prebuilt version can be found here https://github.com/ubports-on-vince/indicator-power/releases/tag/12.10.8

**Comment by Vince1171** [comment]
It works for Oneplus 3T too

**Comment by 0312birdzhang** [comment]
Pull request is here https://github.com/ubports/indicator-power/pull/19
