### ISSUE TITLE
Project is missing proper po/gettext setup

### ISSUE THREAD

**Issue by Flohack74** [ubports/indicator-power#4]
This project is missing the usual po/gettext setup - a subdirectory named po with .pot and .po files inside. As long as this issue is not fixed we cannot integrate it into Weblate.

**Comment by dobey** [comment]
Looks like you need to resync from the trunk on Launchpad. I fixed this there in Feb 2017.

**Comment by cibersheep** [comment]
Oh, this is why "Flashlight" under indicator is not translated...

**Comment by Flohack74** [comment]
Yes and a lot of other indicators have the same...

**Comment by cibersheep** [comment]
I see, I was checking the others too...

**Comment by dobey** [comment]
Again, to go along with my previous comment, I think first priority should be to get everything synced up to the latest upstream changes from the canonical builds. It will be much easier to fix some of the problems after that, rather than trying to re-invent some of the same fixes due to things being lost in migrating over.

**Comment by dobey** [comment]
Closing this, as weblate now has the translations and template from the indicator.

**Comment by Flohack74** [comment]
Still the word "Flashlight" seems not to be in the pot file. Needs regenerating maybe?

**Comment by cibersheep** [comment]
It's not in the [pot](https://github.com/ubports/indicator-power/blob/xenial/po/indicator-power.pot)
Will the pot get updated on the next build, I guess

**Comment by Flohack74** [comment]
Yes but people tend to not check it in... ;)

**Comment by dobey** [comment]
Yes, I suppose it maybe needs regenerated if new strings were added since the last time the pot was updated. That seems to be the case, as the "flashlight" code was added by ubports later.
